let space=' ';
let he='hello';
   document.write(he);
   document.write(space);
   console.log(he);
   alert(he);
 let ow='owu';
   document.write(ow);
   document.write(space);
   console.log(ow);
   alert(ow);
 let co='com';
   document.write(co);
   document.write(space);
   console.log(co);
   alert(co);
 let u='ua';
   document.write(u);
   document.write(space);
   console.log(u);
   alert(u);
 let num1=1;
   document.write(num1);
   document.write(space);
   console.log(num1);
   alert(num1);
 let num2=10;
   document.write(num2);
   document.write(space);
   console.log(num2);
   alert(num2);
 let num3=-999;
   document.write(num3);
   document.write(space);
   console.log(num3);
   alert(num3);
 let num4=123;
   document.write(num4);
   document.write(space);
   console.log(num4);
   alert(num4);
 let num5=3.14;
   document.write(num5);
   document.write(space);
   console.log(num5);
   alert(num5);
 let num6=2.7;
   document.write(num6);
   document.write(space);
   console.log(num6);
   alert(num6);
 let num7=16;
   document.write(num7);
   document.write(space);
   console.log(num7);
   alert(num7);
 let tr=true;
   document.write(tr);
   document.write(space);
   console.log(tr);
   alert(tr);
 let fa=false;
   document.write(fa);
   document.write(space);
   console.log(fa);
   alert(fa);
 let firstName='Nazar';
 let middleName='Lyubomirovych';
 let lastName='Voinarovych';
 let person=`</br>${firstName} ${space} ${middleName} ${space} ${lastName}`;
 document.write(person);
 let a=100;
 console.log(typeof a);
 let b='100';
 console.log(typeof b);
 let c=true;
 console.log(typeof c);
 
 let name=prompt('What is your name?');
 let miName=prompt('What is your middlename?');
 let age=prompt('How old are you?');
 console.log(name,miName,age);

